name: In Cron

# Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "30 12 * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # Secret env
    environment: dev
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT_LOGIN: ${{ secrets.ENDPOINT_LOGIN }}
          ENDPOINT_MASUK: ${{ secrets.ENDPOINT_MASUK }}
          ENDPOINT_PULANG: ${{ secrets.ENDPOINT_PULANG }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          TOKEN=$(curl --location --request POST $ENDPOINT_LOGIN \
          --header "api-key: $API_KEY" \
          --header "Authorization: $API_TOKEN" \
          --header 'Cookie: ci_session=rqmp4n5l887iugatcdd86oq3ajt9fi91' \
          --form "username=$USERNAME" \
          --form "password=$PASSWORD" | jq -r '.data.token')

          curl --location --request POST $ENDPOINT_MASUK \
          --header "api-key: $API_KEY" \
          --header "Authorization: Bearer $TOKEN" \
          --form 'id_pegawai="14"' \
          --form 'lokasi="Raya Tech & Raya Workspace

          Karang Malang,
          Caturtunggal,
          Kec. Depok,
          Kabupaten Sleman,
          Daerah Istimewa Yogyakarta 55281 "' \
          --form 'qr_code="O6ksuIYl6zSFPYAofLxTQD8pMM5SkQC5"' \
          --form 'devices_id="09a7e8144e5f15d0"' \
          --form 'devices_model="SM-M526BR"' \
          --form 'latitude="-7.7773554"' \
          --form 'longitude="110.3836176"' \
          --form 'suhu_tubuh="0"' \
          --form 'keterangan=""' \
          --form 'flag_qr_code="Y"' \
          --form 'flag_radius="Y"' \
          --form 'flag_suhu_tubuh="N"'
