name: In Cron

# Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        env:
          ENDPOINT_LOGIN: ${{ secrets.ENDPOINT_LOGIN }}
      - name: Check Env
        run: echo $ENDPOINT_LOGIN
      # Runs a single command using the runners shell
      - name: Run file login.sh
        run: sh login.sh
